spring:
  datasource:
    url: postgresql://auth_db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
      idle-timeout: 60000
      minimum-idle: 2
      initialization-fail-timeout: -1

jwt:
  secret: ${JWT_SECRET}